name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }} # Setting AWS_REGION as a job-level environment variable
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=plan.cache

      - name: Save Plan as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: plan
          path: plan.cache

      - name: Apply Plan (Manual Trigger)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: terraform apply plan.cache

      - name: Terraform Destroy (Manual Trigger)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: terraform destroy -auto-approve
